import { Barraca, Edicao, Participacao, Pessoa, TurmaFormacao, Usuario } from "./types";
import { nowIso, uid } from "./utils";

export function criarSeed() {
  const edicaoAtual: Edicao = {
    id: "edi_100",
    numero: 100,
    ano: 2026,
    inicio: "2026-08-01",
    fim: "2026-08-31",
    status: "ativa",
  };

  const edicaoAnterior: Edicao = {
    id: "edi_99",
    numero: 99,
    ano: 2025,
    inicio: "2025-08-01",
    fim: "2025-08-31",
    status: "encerrada",
  };

  const barracas: Barraca[] = [
    {
      id: "bar_macarrao",
      edicaoId: edicaoAtual.id,
      nome: "Macarronada",
      setor: "Alimentação",
      vagas: { coordenador: 2, equipista: 30, apoio: 5 },
    },
    {
      id: "bar_pastel",
      edicaoId: edicaoAtual.id,
      nome: "Pastel",
      setor: "Alimentação",
      vagas: { coordenador: 2, equipista: 25, apoio: 4 },
    },
    {
      id: "bar_bebidas",
      edicaoId: edicaoAtual.id,
      nome: "Bebidas",
      setor: "Externa",
      vagas: { coordenador: 1, equipista: 12, apoio: 2 },
    },
    {
      id: "bar_caixa",
      edicaoId: edicaoAtual.id,
      nome: "Caixa",
      setor: "Interna",
      vagas: { coordenador: 1, equipista: 10, apoio: 1 },
    },
    {
      id: "bar_pizza",
      edicaoId: edicaoAtual.id,
      nome: "Pizza",
      setor: "Alimentação",
      vagas: { coordenador: 2, equipista: 20, apoio: 3 },
    },
  ];

  const pessoas: Pessoa[] = [
    {
      id: "pes_ana",
      cracha: 12,
      nome: "Ana Maria Rossi",
      nascimento: "1978-03-15",
      telefone: "(11) 98765-4321",
      email: "ana.rossi@example.com",
      bairro: "Bixiga",
      estadoCivil: "Casado(a)",
      ativo: true,
      dadosValidados: true,
      filhos: [
        { id: uid("fil"), nome: "Luca Rossi", nascimento: "2014-05-10", frequentaRecreacao: true },
      ],
      criadoEm: nowIso(),
      atualizadoEm: nowIso(),
    },
    {
      id: "pes_bruno",
      cracha: 27,
      nome: "Bruno de Lucca",
      nascimento: "1985-09-22",
      telefone: "(11) 99887-1122",
      email: "bruno@example.com",
      bairro: "Aclimação",
      estadoCivil: "Solteiro(a)",
      ativo: true,
      dadosValidados: false,
      filhos: [],
      criadoEm: nowIso(),
      atualizadoEm: nowIso(),
    },
    {
      id: "pes_carla",
      cracha: 33,
      nome: "Carla Santoro",
      nascimento: "1990-12-01",
      telefone: "(11) 97654-3210",
      email: "carla.s@example.com",
      bairro: "Mooca",
      estadoCivil: "Casado(a)",
      ativo: true,
      dadosValidados: true,
      filhos: [],
      criadoEm: nowIso(),
      atualizadoEm: nowIso(),
    },
    {
      id: "pes_diego",
      cracha: 41,
      nome: "Diego Marinelli",
      nascimento: "1972-06-30",
      telefone: "(11) 91234-5678",
      bairro: "Bela Vista",
      estadoCivil: "Casado(a)",
      ativo: true,
      dadosValidados: false,
      filhos: [],
      criadoEm: nowIso(),
      atualizadoEm: nowIso(),
    },
    {
      id: "pes_elena",
      cracha: 58,
      nome: "Elena Bonfanti",
      nascimento: "1995-04-18",
      telefone: "(11) 95678-1234",
      email: "elena.b@example.com",
      bairro: "Tatuapé",
      estadoCivil: "Solteiro(a)",
      ativo: true,
      dadosValidados: true,
      filhos: [],
      criadoEm: nowIso(),
      atualizadoEm: nowIso(),
    },
  ];

  const participacoes: Participacao[] = [
    {
      id: "par_1",
      pessoaId: "pes_ana",
      edicaoId: edicaoAtual.id,
      barracaId: "bar_macarrao",
      funcao: "Coordenador",
      formacaoFeita: true,
      dataFormacao: "2026-07-12T19:00:00Z",
      crachaEntregue: true,
      dataEntregaCracha: "2026-07-30T14:00:00Z",
      criadoEm: nowIso(),
    },
    {
      id: "par_2",
      pessoaId: "pes_bruno",
      edicaoId: edicaoAtual.id,
      barracaId: "bar_pastel",
      funcao: "Equipista",
      formacaoFeita: false,
      crachaEntregue: false,
      criadoEm: nowIso(),
    },
    {
      id: "par_3",
      pessoaId: "pes_carla",
      edicaoId: edicaoAtual.id,
      barracaId: "bar_caixa",
      funcao: "Coordenador",
      formacaoFeita: true,
      dataFormacao: "2026-07-12T19:00:00Z",
      crachaEntregue: false,
      criadoEm: nowIso(),
    },
    {
      id: "par_4",
      pessoaId: "pes_elena",
      edicaoId: edicaoAtual.id,
      barracaId: "bar_pizza",
      funcao: "Equipista",
      formacaoFeita: true,
      dataFormacao: "2026-07-12T19:00:00Z",
      crachaEntregue: true,
      dataEntregaCracha: "2026-07-30T14:30:00Z",
      criadoEm: nowIso(),
    },
    {
      id: "par_h_99_ana",
      pessoaId: "pes_ana",
      edicaoId: edicaoAnterior.id,
      barracaId: "bar_macarrao",
      funcao: "Equipista",
      formacaoFeita: true,
      crachaEntregue: true,
      criadoEm: nowIso(),
    },
    {
      id: "par_h_99_bruno",
      pessoaId: "pes_bruno",
      edicaoId: edicaoAnterior.id,
      barracaId: "bar_bebidas",
      funcao: "Equipista",
      formacaoFeita: true,
      crachaEntregue: true,
      criadoEm: nowIso(),
    },
  ];

  const turmas: TurmaFormacao[] = [
    {
      id: "tur_1",
      edicaoId: edicaoAtual.id,
      data: "2026-07-12",
      horario: "19:00",
      local: "Salão paroquial Achiropita",
      instrutor: "Pe. Antonio",
      capacidade: 80,
    },
    {
      id: "tur_2",
      edicaoId: edicaoAtual.id,
      data: "2026-07-19",
      horario: "19:00",
      local: "Salão paroquial Achiropita",
      instrutor: "Equipe de coordenação",
      capacidade: 80,
    },
  ];

  const usuarios: Usuario[] = [
    {
      id: "usr_adm",
      nome: "Administrador",
      email: "admin@achiropita.app",
      senha: "achiropita100",
      perfil: "ADM",
    },
    {
      id: "usr_org",
      nome: "Organização Geral",
      email: "org@achiropita.app",
      senha: "achiropita100",
      perfil: "ORG",
    },
    {
      id: "usr_eqp",
      nome: "Ana Maria Rossi",
      email: "ana.rossi@example.com",
      senha: "achiropita100",
      perfil: "EQP",
      pessoaId: "pes_ana",
    },
  ];

  return {
    usuarios,
    pessoas,
    edicoes: [edicaoAtual, edicaoAnterior],
    barracas,
    participacoes,
    turmas,
    auditoria: [],
  };
}
