import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Ban,
  BarChart3,
  Braces,
  Calendar,
  CalendarCheck2,
  Camera,
  Car,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Copy,
  Crop,
  Download,
  Eye,
  ExternalLink,
  Grid3x3,
  HelpCircle,
  History,
  Link,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  Repeat,
  ScanLine,
  Search,
  Send,
  Target,
  Star,
  StarOff,
  Trash2,
  User,
  UserX,
  Users,
  Wand2,
  X,
  type LucideIcon,
  NotebookPen,
  ParkingCircle,
} from "lucide-react";

const icones: Record<string, LucideIcon> = {
  "seta-esquerda": ArrowLeft,
  "seta-direita": ArrowRight,
  mais: Plus,
  fechar: X,
  check: Check,
  checkin: CheckCheck,
  entrar: LogIn,
  abrir: ExternalLink,
  sair: LogOut,
  lapis: Pencil,
  estrela: Star,
  "estrela-desfazer": StarOff,
  lixeira: Trash2,
  olho: Eye,
  historico: History,
  scan: ScanLine,
  qr: QrCode,
  impressora: Printer,
  copiar: Copy,
  link: Link,
  proibido: Ban,
  presenca: CalendarCheck2,
  recarregar: RefreshCw,
  baixar: Download,
  enviar: Send,
  usuario: User,
  "usuario-x": UserX,
  usuarios: Users,
  carro: Car,
  relatorioestacionamento: ParkingCircle,
  cadeado: Lock,
  "cadeado-aberto": LockOpen,
  camera: Camera,
  cortar: Crop,
  alvo: Target,
  calendario: Calendar,
  ajuda: HelpCircle,
  busca: Search,
  trocar: Repeat,
  topo: ArrowUp,
  "seta-baixo": ChevronDown,
  chat: MessageCircle,
  email: Mail,
  chaves: Braces,
  varinha: Wand2,
  alerta: AlertTriangle,
  "check-circular": CheckCircle2,
  avaliar: NotebookPen,
  grade: Grid3x3,
  "relatorio": BarChart3,
  "clipboard": ClipboardList,
  "recolher": PanelLeftClose,
  "expandir": PanelLeftOpen,
  MapPin: MapPin,
};

interface IconeProps {
  nome: string;
  tamanho?: number;
  className?: string;
}

export function Icone({ nome, tamanho = 24, className }: IconeProps) {
  const IconeLucide = icones[nome];
  if (!IconeLucide) return null;
  return <IconeLucide size={tamanho} className={className} aria-hidden="true" />;
}
